use_frameworks!

platform :ios, '8.0'

target 'FSEditVideo_Example' do
  pod 'FSEditVideo', :path => '../'

  target 'FSEditVideo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
